apiVersion: kpack.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: tcserverbuilder
spec:
  order:
  - group:
    - id: paketo-buildpacks/bellsoft-liberica
      version: 7.0.0
    - id: vmware-tcserver-buildpack
      version: 4.1.7
  - group:
    - id: tanzu-buildpacks/java-native-image
      version: 4.0.0
  - group:
    - id: tanzu-buildpacks/java
      version: 5.0.0
  - group:
    - id: tanzu-buildpacks/nodejs
      version: 1.2.3
  - group:
    - id: tanzu-buildpacks/dotnet-core
      version: 1.0.1
  - group:
    - id: tanzu-buildpacks/go
      version: 1.0.9
  - group:
    - id: tanzu-buildpacks/php
      version: 0.0.5
  - group:
    - id: tanzu-buildpacks/nginx
      version: 0.0.48
  - group:
    - id: tanzu-buildpacks/httpd
      version: 0.0.40
  - group:
    - id: paketo-buildpacks/procfile
      version: 4.0.0    
  serviceAccountRef:
    name: canonical-registry-serviceaccount
    namespace: kpack
  stack:
    kind: ClusterStack
    name: base
  store:
    kind: ClusterStore
    name: default
  tag: lsilva.azurecr.io/lsilva/tcserverbuilder
status:
  builderMetadata:
  - homepage: https://github.com/paketo-buildpacks/graalvm
    id: vmware-tcserver-buildpack
    version: 4.1.7
  - homepage: https://github.com/paketo-buildpacks/bellsoft-liberica
    id: paketo-buildpacks/bellsoft-liberica
    version: 7.0.0    
  - homepage: https://github.com/paketo-buildpacks/graalvm
    id: paketo-buildpacks/graalvm
    version: 5.0.0
  - id: tanzu-buildpacks/go-dist
    version: 0.1.3
  - id: tanzu-buildpacks/php-dist
    version: 0.0.44
  - id: tanzu-buildpacks/dotnet-core-sdk
    version: 0.1.0
  - id: tanzu-buildpacks/node-engine
    version: 0.1.2
  - id: tanzu-buildpacks/node-engine
    version: 0.1.3
  - homepage: https://github.com/pivotal-cf/tanzu-apache-skywalking
    id: tanzu-buildpacks/apache-skywalking
    version: 3.0.0
  - id: tanzu-buildpacks/dotnet-core-runtime
    version: 0.1.2
  - homepage: https://github.com/pivotal-cf/tanzu-jprofiler
    id: tanzu-buildpacks/jprofiler
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/gradle
    id: paketo-buildpacks/gradle
    version: 4.0.0
  - homepage: https://github.com/pivotal-cf/tanzu-appdynamics
    id: tanzu-buildpacks/appdynamics
    version: 3.0.0
  - id: tanzu-buildpacks/dotnet-core-aspnet
    version: 0.1.0
  - homepage: https://github.com/pivotal-cf/tanzu-new-relic
    id: tanzu-buildpacks/new-relic
    version: 3.0.0
  - homepage: https://github.com/pivotal-cf/tanzu-overops
    id: tanzu-buildpacks/overops
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/apache-tomcat
    id: paketo-buildpacks/apache-tomcat
    version: 4.2.0
  - id: tanzu-buildpacks/icu
    version: 0.0.9
  - homepage: https://github.com/pivotal-cf/tanzu-jrebel
    id: tanzu-buildpacks/jrebel
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/sbt
    id: paketo-buildpacks/sbt
    version: 4.0.0
  - homepage: https://github.com/paketo-buildpacks/azure-application-insights
    id: paketo-buildpacks/azure-application-insights
    version: 4.0.0
  - id: tanzu-buildpacks/httpd
    version: 0.0.40
  - id: tanzu-buildpacks/httpd
    version: 0.0.39
  - homepage: https://github.com/pivotal-cf/tanzu-contrast-security
    id: tanzu-buildpacks/contrast-security
    version: 3.0.0
  - id: tanzu-buildpacks/nginx
    version: 0.0.46
  - id: tanzu-buildpacks/nginx
    version: 0.0.48
  - homepage: https://github.com/paketo-buildpacks/maven
    id: paketo-buildpacks/maven
    version: 4.0.0
  - homepage: https://github.com/pivotal-cf/tanzu-elastic-apm
    id: tanzu-buildpacks/elastic-apm
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/google-stackdriver
    id: paketo-buildpacks/google-stackdriver
    version: 3.0.0
  - id: tanzu-buildpacks/php-web
    version: 0.0.25
  - id: tanzu-buildpacks/dep
    version: 0.0.10
  - homepage: https://github.com/pivotal-cf/tanzu-yourkit
    id: tanzu-buildpacks/yourkit
    version: 3.0.0
  - id: tanzu-buildpacks/php-composer
    version: 0.0.31
  - id: tanzu-buildpacks/yarn
    version: 0.0.2
  - homepage: https://github.com/pivotal-cf/tanzu-dynatrace
    id: tanzu-buildpacks/dynatrace
    version: 3.0.0
  - id: tanzu-buildpacks/dotnet-publish
    version: 0.1.0
  - id: tanzu-buildpacks/dotnet-execute
    version: 0.1.0
  - homepage: https://github.com/pivotal-cf/tanzu-jacoco
    id: tanzu-buildpacks/jacoco
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/spring-boot
    id: paketo-buildpacks/spring-boot
    version: 4.0.0
  - homepage: https://github.com/pivotal-cf/tanzu-synopsys
    id: tanzu-buildpacks/synopsys
    version: 3.0.0
  - id: tanzu-buildpacks/yarn-install
    version: 0.1.2
  - homepage: https://github.com/pivotal-cf/tanzu-checkmarx
    id: tanzu-buildpacks/checkmarx
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/ca-certificates
    id: paketo-buildpacks/ca-certificates
    version: 2.0.0
  - homepage: https://github.com/paketo-buildpacks/encrypt-at-rest
    id: paketo-buildpacks/encrypt-at-rest
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/debug
    id: paketo-buildpacks/debug
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/leiningen
    id: paketo-buildpacks/leiningen
    version: 2.0.0
  - homepage: https://github.com/paketo-buildpacks/jmx
    id: paketo-buildpacks/jmx
    version: 3.0.0
  - homepage: https://github.com/pivotal-cf/tanzu-snyk
    id: tanzu-buildpacks/snyk
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/spring-boot-native-image
    id: paketo-buildpacks/spring-boot-native-image
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/executable-jar
    id: paketo-buildpacks/executable-jar
    version: 4.0.0
  - id: tanzu-buildpacks/go-build
    version: 0.0.23
  - homepage: https://github.com/paketo-buildpacks/environment-variables
    id: paketo-buildpacks/environment-variables
    version: 3.0.0
  - homepage: https://github.com/pivotal-cf/tanzu-aspectj
    id: tanzu-buildpacks/aspectj
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/procfile
    id: paketo-buildpacks/procfile
    version: 4.0.0
  - homepage: https://github.com/paketo-buildpacks/image-labels
    id: paketo-buildpacks/image-labels
    version: 3.0.0
  - homepage: https://github.com/paketo-buildpacks/dist-zip
    id: paketo-buildpacks/dist-zip
    version: 3.0.0
  - id: tanzu-buildpacks/npm-install
    version: 0.1.1
  - id: tanzu-buildpacks/dep-ensure
    version: 0.0.29
  - id: tanzu-buildpacks/yarn-start
    version: 0.0.4
  - id: tanzu-buildpacks/npm-start
    version: 0.0.2
  - id: tanzu-buildpacks/go-mod-vendor
    version: 0.0.26
  - id: tanzu-buildpacks/node-start
    version: 0.0.3
  - homepage: https://github.com/pivotal-cf/tanzu-java
    id: tanzu-buildpacks/java
    version: 5.0.0
  - homepage: https://github.com/pivotal-cf/tanzu-java-native-image
    id: tanzu-buildpacks/java-native-image
    version: 4.0.0
  - id: tanzu-buildpacks/dotnet-core
    version: 1.0.1
  - id: tanzu-buildpacks/nodejs
    version: 1.2.3
  - id: tanzu-buildpacks/php
    version: 0.0.5
  - id: tanzu-buildpacks/go
    version: 1.0.9    
  order:
  - group:
    - id: paketo-buildpacks/bellsoft-liberica
      version: 7.0.0
    - id: vmware-tcserver-buildpack
      version: 4.1.7
  - group:
    - id: tanzu-buildpacks/java-native-image
      version: 4.0.0
  - group:
    - id: tanzu-buildpacks/java
      version: 5.0.0
  - group:
    - id: tanzu-buildpacks/nodejs
      version: 1.2.3
  - group:
    - id: tanzu-buildpacks/dotnet-core
      version: 1.0.1
  - group:
    - id: tanzu-buildpacks/go
      version: 1.0.9
  - group:
    - id: tanzu-buildpacks/php
      version: 0.0.5
  - group:
    - id: tanzu-buildpacks/nginx
      version: 0.0.48
  - group:
    - id: tanzu-buildpacks/httpd
      version: 0.0.40
  - group:
    - id: paketo-buildpacks/procfile
      version: 4.0.0
  os: linux
  stack:
    id: io.buildpacks.stacks.bionic
    runImage: lsilva.azurecr.io/lsilva/run@sha256:70accedc26b4d9230ce6ae4b1e55a0588bb14447e074d8fc65bd3ced4211630b
