apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-client-pv
spec:
  storageClassName: nfs-client-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "10.197.78.151"
    path: "/exports"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-client-pvc
spec:
  storageClassName: nfs-client-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi    