apiVersion: v1
kind: Pod
metadata:
  name: nfs-client-pod-1
spec:
  containers:
  - name: busybox
    image: "k8s.gcr.io/busybox"
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh","-c","echo \"Hello from pod 1!\" > /nfs/pod1output.txt;"]
    volumeMounts:
    - name: nfs-vol
      mountPath: "/nfs"
    command: [ "sleep", "1000000" ]
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: nfs-client-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-client-pod-2
spec:
  containers:
  - name: busybox
    image: "k8s.gcr.io/busybox"
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh","-c","echo \"Hello from pod 2!\" > /nfs/pod2output.txt;"]
    volumeMounts:
    - name: nfs-vol
      mountPath: "/nfs"
    command: [ "sleep", "1000000" ]
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: nfs-client-pvc        