apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-custom
  name: nginx-custom
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-custom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-custom
    spec:
      containers:
      - image: nginx
        name: nginx
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh","-c","export MYIP=$(hostname -I);echo \"<!DOCTYPE html><html><body><h1>Welcome to nginx - $MYIP !</h1></body></html>\" > /usr/share/nginx/html/index.html;"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-custom
  name: nginx-custom-svc
  namespace: demo
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx-custom
  type: ClusterIP          