apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tcs-app2
  name: tcs-app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcs-app2
  # strategy: {}
  template:
    metadata:
      labels:
        app: tcs-app2
    spec:
      containers:
      - image: lsilva.azurecr.io/tcs-app2
        name: tcs-app2
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tcs-app2
  name: tcs-app2-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tcs-app2
  type: LoadBalancer