apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: myapp-root
  namespace: weighted-routing
spec: 
  virtualhost:
    fqdn: myapp.go.haas-208.pez.pivotal.io
  routes: 
  - match: /
    services:
      - name: myapp-svc-10
        port: 80
        weight: 90
      - name: myapp-svc-11
        port: 80
        weight: 10    
