apiVersion: v1
kind: Pod
metadata:
  name: rwx-pod1
spec:
  nodeSelector:
    spec.ip: 172.28.2.3
  containers:
  - name: busybox
    image: "k8s.gcr.io/busybox"
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh","-c","echo \"Hello from pod 1!\" > /test-volume/pod1output.txt;"]
    volumeMounts:
    - name: test-volume
      mountPath: /test-volume
    command: [ "sleep", "1000000" ]
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: nfs-rwx-pvc           
---
apiVersion: v1
kind: Pod
metadata:
  name: rwx-pod2
spec:
  nodeSelector:
    spec.ip: 172.28.2.3
  containers:
  - name: busybox
    image: "k8s.gcr.io/busybox"
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh","-c","echo \"Hello from pod 2!\" > /test-volume/pod2output.txt;"]
    volumeMounts:
    - name: test-volume
      mountPath: /test-volume
    command: [ "sleep", "1000000" ]
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: nfs-rwx-pvc           
