apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata: 
  name: blue-green-root
  namespace: bluegreen
spec: 
  virtualhost:
    fqdn: myservice.tkg.haas-426.pez.pivotal.io
  routes: 
    - conditions:
      - prefix: /  
      services:
        - name: blue-svc
          port: 80
          weight: 0
        - name: green-svc
          port: 80
          weight: 100        