kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-lun
  annotations:
    volume.beta.kubernetes.io/storage-class: lun
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi