apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredevopsagent
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azuredevopsagent
  template:
    metadata:
      labels:
        app: azuredevopsagent
    spec:
      containers:
      - name: azuredevopsagent
        image: silval/azure-devops-agent:latest
        env:
        - name: AZP_URL
          value: https://dev.azure.com/lsilva0356
        - name: AZP_POOL
          value: Default
        # - name: AZP_AGENT_NAME   # the pod ID will be used as agent name when this variable is ommitted
        #   value: k8s-agent-tkg-azurearc-
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azuredevops
              key: AZP_TOKEN 
        - name: DOCKER_HOST
          value: tcp://localhost:2375   
      - name: dind
        image: docker:18.06.3-dind
        ## for 19.03+ versions, TLS is enabled by default and needs to be configured for docker daemon connectivity to work
        ## DOCKER_TLS_CERTDIR - see https://hub.docker.com/_/docker?tab=description&page=3&name=dind
        args: 
        - "--insecure-registry=10.197.19.68"
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker                       
      volumes:
      - name: dind-storage
        emptyDir: {}             
